import type { InventoryItem } from '../types';

export const mockInventory: InventoryItem[] = [
  {
    id: '1',
    name: 'Paracetamol 500mg',
    sku: 'MED-001',
    category: 'Medicine',
    quantity: 150,
    minStockLevel: 50,
    price: 5.00,
    expiryDate: '2026-12-31',
    location: 'Shelf A-1',
    status: 'In Stock',
  },
  {
    id: '2',
    name: 'Surgical Masks (50pcs)',
    sku: 'SUP-002',
    category: 'Supplies',
    quantity: 20,
    minStockLevel: 30,
    price: 15.00,
    location: 'Shelf B-3',
    status: 'Low Stock',
  },
  {
    id: '3',
    name: 'Vitamin C 1000mg',
    sku: 'MED-003',
    category: 'Medicine',
    quantity: 0,
    minStockLevel: 20,
    price: 12.50,
    expiryDate: '2025-08-15',
    location: 'Shelf A-2',
    status: 'Out of Stock',
  },
  {
    id: '4',
    name: 'Bandages Assorted',
    sku: 'SUP-004',
    category: 'Supplies',
    quantity: 85,
    minStockLevel: 10,
    price: 4.50,
    location: 'Shelf B-1',
    status: 'In Stock',
  },
  {
    id: '5',
    name: 'Ibuprofen 200mg',
    sku: 'MED-005',
    category: 'Medicine',
    quantity: 45,
    minStockLevel: 100,
    price: 6.00,
    expiryDate: '2026-05-20',
    location: 'Shelf A-1',
    status: 'Low Stock',
  },
];
